name: ci

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn run lint

      - name: Run tests
        run: yarn run test

      - name: Install nmap
        run: |
          sudo apt update
          sudo apt install -yq nmap

      - name: Run e2e tests
        run: |
          docker pull ghcr.io/gartnera/ctf-sshd:latest
          yarn run e2e
